version: '2'

services:
    database:
        image: postgres:9.6-alpine
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - ~iix/iix-notes-db:/docker-entrypoint-initdb.d:Z
        ports:
            - 5432:5432

    backend:
        image: loll3k/iix.se-rust-backend
#       environment:
#           WEBROOT: "/api"
#           DBHOST: database:5432
#           DBUSER: www-data
#           DBPASS: www-data
#           DBNAME: iix-notes
#           JWT: debug
        ports:
            - "80:80"
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
